### ISSUE TITLE
Adicionar documentação das rotas seguindo modelo indicado

### ISSUE THREAD

**Issue by danieltidus** [anniellecrispim/Guild_Mannagent_Resource#1]
Atualizar o readme para contemplar a documentação dos controllers com descrição, códigos de retorno possíveis, exemplos de retornos de dados e mensagens de erro padrão.

**Comment by Doge-Sma** [comment]
Ta feito, fiz o Commit antes da meia noite, fiz algumas alterações da forma que tava no modelo por a gente ainda não ter os services, amanhã no encontro com o senhor eu falo mais a respeito
